exec(open('quotes.py').read())
Q2={
'love':Q['love']+["Love is knowing their coffee order and their bad days.","Busy is a reason, not an excuse. Tell them which one it is.","The right person makes ordinary days feel like a plan.","Hold hands in public. Hold space in private.","Fight the problem, not the person.","Distance is just love with a longer commute.","Text first. Pride is a lonely roommate.","Real love sounds like \"did you eat?\""],
'motivation':Q['motivation']+["You don't need a new year. You need a new hour.","Small steps still leave footprints.","The goal is far. The step is near. Take the step.","Stop negotiating with the alarm.","Your excuses are well written. Your results could be too.","Bad day, good work. Both can be true.","Momentum loves a messy start.","If it scares you and excites you, it's probably the one."],
'god':Q['god']+["Whatever you're carrying, you can set it down for a minute.","Faith doesn't remove the storm. It changes who is in the boat.","Thank Him in the waiting room too.","Nothing is wasted. Not even the detour.","Some answers come as strength, not solutions.","Prayer is the shortest distance between worry and rest.","Be still. You are not the only one working on this.","Gratitude at dawn, trust at dusk."],
'naughty':["Be good. And if you can't be good, be gorgeous about it.","Flirt with your own life a little.","Trouble is just fun that hasn't met your parents yet.","Send the risky text. Blame the moon.","Behave? In this economy?","Eye contact held one second too long is a love letter.","I'm not late. I'm making an entrance.","Wear the outfit that makes you walk differently.","Never trust a quiet person with a smirk.","Dessert first. Apologise later.","Be the plot twist in someone's boring week.","Kiss like you're late for something good.","Tease gently. Mean it fondly.","A little mischief keeps a long marriage young.","Rules are just suggestions with better PR.","Whisper it. It lands harder.","Dress like you know a secret.","Be unpredictable on a Tuesday.","Some people are a bad idea you'd repeat.","Raise one eyebrow. Let them wonder.","Stay up late. Talk about nothing. Mean everything.","Be the kind of dangerous that makes people braver.","Say yes to the second drink and the first adventure.","Good manners get you in. Bad ideas get you the story."],
'building':Q['building']+["Fix the leaky bucket before you pour in more water.","Ask what job the user is hiring your product to do.","Your roadmap is a guess. Your users are the truth.","Automate the boring. Hand-craft the memorable.","A feature nobody asked for is a cost nobody budgeted.","The best code is the code you didn't have to write.","Great products feel like someone cared at 2am.","Launch day is a rumour. Every day is launch day."]}
if __name__=='__main__':
    print({k:len(v) for k,v in Q2.items()},sum(len(v) for v in Q2.values()),len({x for v in Q2.values() for x in v}))
